# Generated by Django 3.2 on 2022-12-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passport',
            old_name='employees',
            new_name='employee',
        ),
    ]
